[theme]
primaryColor = "#00D9A3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F8F7"
textColor = "#2C3E50"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false